trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-requiredpayments
      type: github
      name: SkillsFundingAgency/das-payments-v2-requiredpayments
      endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
  # TODO - Readd back in once PV2-3711 is in main
#- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml