parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.RequiredPayments
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml


   # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.Application/SFA.DAS.Payments.RequiredPayments.Application.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Application/SFA.DAS.Payments.RequiredPayments.Application.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Application/SFA.DAS.Payments.RequiredPayments.Application.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.Domain/SFA.DAS.Payments.RequiredPayments.Domain.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Domain/SFA.DAS.Payments.RequiredPayments.Domain.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Domain/SFA.DAS.Payments.RequiredPayments.Domain.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'




  # task: NuGetCommand@2 - src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.Application/SFA.DAS.Payments.RequiredPayments.Application.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService/SFA.DAS.Payments.RequiredPayments.ClawbackRemovedLearnerService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.Domain/SFA.DAS.Payments.RequiredPayments.Domain.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces/SFA.DAS.Payments.RequiredPayments.RemovedLearnerService.Interfaces.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsProxyService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces/SFA.DAS.Payments.RequiredPayments.RequiredPaymentsService.Interfaces.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'


  - task: DotNetCoreCLI@2
    displayName: "Publish src/SFA.DAS.Payments.RequiredPayments.Messages"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish src/SFA.DAS.Payments.RequiredPayments.Model"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true


      

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.RequiredPayments.Messages/SFA.DAS.Payments.RequiredPayments.Messages.csproj;
        src/SFA.DAS.Payments.RequiredPayments.Model/SFA.DAS.Payments.RequiredPayments.Model.csproj;